install.packages("Rcpp")
install.packages("shinydashboard")
install.packages("shinycssloaders")
install.packages("markdown")
install.packages("xml2", configure.vars="PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig")
install.packages("tidyverse")
install.packages("lubridate")
