install.packages("Rcpp")
install.packages("shinydashboard")
install.packages("shinycssloaders")
install.packages("markdown")
install.packages("xml2", configure.vars="PKG_CONFIG_PATH=/usr/local/lib/pkgconfig")
install.packages("tidyverse")
install.packages("lubridate")
