install.packages("Rcpp")
install.packages("shinydashboard")
install.packages("shinycssloaders")
install.packages("markdown")
install.packages("xml2", configure.vars="INCLUDE_DIR=/usr/include/libxml2/libxml LIB_DIR=/usr/lib/x86_64-linux-gnu/")
install.packages("tidyverse")
install.packages("lubridate")
